project:
  type: website
  resources:
    - "CNAME"

execute:
  freeze: true

website:
  title: "tidyomicsBlog"
  site-url: https://blog.bioconductor.org/
  description: "The Tidyomics Blog"
  open-graph: true
  navbar:
    right:
      - about.qmd
      - contributing.qmd
      - icon: github
        href: https://github.com/tidyomics/tidyomicsBlog
      - icon: rss
        href: index.xml
  body-footer: |
    <p>© 2025 Bioconductor. Content is published under <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons CC-BY-4.0 License</a> for the text and <a href="https://opensource.org/licenses/BSD-3-Clause">BSD 3-Clause License</a> for any code. | <a href="https://www.r-bloggers.com">R-Bloggers</a></p>
format:
  html:
    theme: yeti
    css: styles.css
    include-in-header:
    # Override default Quarto icons to enable newer icons like bi-bluesky (v1.12+)
    # Uses CDN-pinned version for reproducibility
      text: |
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.css" rel="stylesheet">
      